pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id 'com.android.application' version '8.7.3'
        id 'org.jetbrains.kotlin.android' version '1.9.24'
    }
}
dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_PROJECT
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
    }
}
rootProject.name = "WakeupSchedule"
include ':app'
include ':gxuJwxtJavaClient'